In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Uber.csv")
data

    dispatching_base_number       date  active_vehicles  trips
0                    B02512   1/1/2015              190   1132
1                    B02765   1/1/2015              225   1765
2                    B02764   1/1/2015             3427  29421
3                    B02682   1/1/2015              945   7679
4                    B02617   1/1/2015             1228   9537
..                      ...        ...              ...    ...
349                  B02764  2/28/2015             3952  39812
350                  B02617  2/28/2015             1372  14022
351                  B02682  2/28/2015             1386  14472
352                  B02512  2/28/2015              230   1803
353                  B02765  2/28/2015              747   7753

[354 rows x 4 columns]

In [5]:
d = data['trips'][:30]
d

0      1132
1      1765
2     29421
3      7679
4      9537
5      6903
6      4768
7      7065
8       875
9      5506
10     1001
11    19974
12     1526
13    10664
14     7432
15     8010
16     1088
17    29729
18      791
19     5621
20     5223
21      993
22     7729
23    20441
24      984
25     6012
26     7899
27    20926
28     5798
29     1133
Name: trips, dtype: int64

In [6]:
import numpy as np
from scipy import stats

# 95% Confidence Interval automatically
ci = stats.t.interval(
    confidence=0.95,
    df=len(d) - 1,
    loc=np.mean(d),
    scale=stats.sem(d)
)

print("95% Confidence Interval:")
print("Lower:", ci[0])
print("Upper:", ci[1])

95% Confidence Interval:
Lower: 4882.616032139624
Upper: 10959.050634527042

In [9]:
population_std = 3

ci = stats.norm.interval(
    0.95,
    loc=np.mean(d),
    scale=population_std / np.sqrt(len(d))
)

print("Number of data:", len(d))
print("Mean:", np.mean(d))

print("95% Confidence Interval:")
print("Lower:", ci[0])
print("Upper:", ci[1])

Number of data: 30
Mean: 7920.833333333333
95% Confidence Interval:
Lower: 7919.759816847103
Upper: 7921.906849819563

In [10]:
#1. 50 students, mean=165, SD=10; 95% CI
student=50
mean=165
sd=10
ci=stats.norm.interval(
    0.95,
    loc=mean,
    scale=sd/np.sqrt(student)
)
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

95% Confidence Interval:
Lower: 162.22819235130063
Upper: 167.77180764869937

In [11]:
#2. Bottle fill mean=500ml, SD=8, n=40; 99% CI
population_std = 8

ci = stats.norm.interval(
    0.99,
    loc=500,
    scale=population_std / 40
)

print("95% Confidence Interval:")
print("Lower:", ci[0])
print("Upper:", ci[1])

95% Confidence Interval:
Lower: 499.48483413929023
Upper: 500.51516586070977

In [12]:
#4. Restaurant rating mean=4.2, SD=0.5, n=80; 90% CI.
population_std = 0.5
mean = 4.2
n = 80
ci = stats.norm.interval(
    0.90,
    loc=mean,
    scale=population_std / n
)

print("95% Confidence Interval:")
print("Lower:", ci[0])
print("Upper:", ci[1])

95% Confidence Interval:
Lower: 4.189719664831554
Upper: 4.210280335168447