In [1]:
import numpy as np
from scipy import stats

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("blood_pressure.csv")
data

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity
0,1,1,11.28,0.90,34,23,1,1.0,0,45961
1,2,0,9.75,0.23,54,33,1,NaN,0,26106
2,3,1,10.79,0.91,70,49,0,NaN,0,9995
3,4,0,11.00,0.43,71,50,0,NaN,0,10635
4,5,1,14.17,0.83,52,19,0,NaN,0,15619
...,...,...,...,...,...,...,...,...,...,...
1995,1996,1,10.14,0.02,69,26,1,NaN,1,26118
1996,1997,1,11.77,1.00,24,45,1,1.0,1,2572
1997,1998,1,16.91,0.22,18,42,0,NaN,0,14933
1998,1999,0,11.15,0.72,46,45,1,NaN,1,18157
1999,2000,1,11.36,0.09,41,45,0,NaN,0,20729

In [12]:
a = data["Level_of_Hemoglobin"]
a

0       11.28
1        9.75
2       10.79
3       11.00
4       14.17
        ...
1995    10.14
1996    11.77
1997    16.91
1998    11.15
1999    11.36
Name: Level_of_Hemoglobin, Length: 2000, dtype: float64

In [41]:
a.head(25)

0     11.28
1      9.75
2     10.79
3     11.00
4     14.17
5     11.64
6     11.69
7     12.70
8     10.88
9     14.56
10     8.58
11    12.77
12    16.40
13    16.42
14    11.97
15    10.96
16    11.98
17    11.60
18     8.99
19    16.55
20    16.95
21    10.85
22    11.19
23    10.61
24    10.26
Name: Level_of_Hemoglobin, dtype: float64

In [35]:
a.tail(30)

1970    11.26
1971    12.53
1972     9.82
1973    11.45
1974     8.47
1975     8.75
1976    12.07
1977    11.16
1978    11.57
1979    11.70
1980    12.34
1981    13.49
1982     9.08
1983    14.56
1984    10.81
1985    10.44
1986    13.63
1987    11.79
1988    17.17
1989    10.84
1990    11.21
1991    15.53
1992     9.38
1993     9.69
1994    11.07
1995    10.14
1996    11.77
1997    16.91
1998    11.15
1999    11.36
Name: Level_of_Hemoglobin, dtype: float64

In [42]:
cal_t = np.array([10.26,10.61,11.19,10.85,16.97,16.55,12.53,10.79,11.15,14.56,8.47,8.75,11.26,8.99,16.55,11.98,10.96,16.42,12.53,9.08,16.91,11.36,9.38,11.77,14.56,11.69,15.53,9.69,11.07,16.91,10.14,13.63,17.17])

In [43]:
len(cal_t)

33

In [48]:
#T-distribution
ci = stats.t.interval(
    confidence = 0.95,
    df = len(cal_t) - 1,
    loc = np.mean(cal_t),
    scale = stats.sem(cal_t)
)

print("Lower limit : " + str(ci[0]))
print("Higher limit : " + str(ci[1]))

Lower limit : 11.43774188888438
Higher limit : 13.426500535358047

In [30]:
b = data["Level_of_Hemoglobin"]
b

0       11.28
1        9.75
2       10.79
3       11.00
4       14.17
        ...
1995    10.14
1996    11.77
1997    16.91
1998    11.15
1999    11.36
Name: Level_of_Hemoglobin, Length: 2000, dtype: float64

In [32]:
cal_ran = np.array([10.79,11.15,16.91,11.36,9.38,11.77,14.56,11.69,15.53,9.69,11.07,16.91,10.14,13.63,17.17])

In [45]:
len(cal_ran)

15

In [46]:
pop_standard = np.std(cal_ran)
pop_standard

np.float64(2.666864992625028)

In [47]:
#Z-distribution
ci = stats.norm.interval(
    0.95,
    loc = np.mean(cal_ran),
    scale = pop_standard / np.sqrt(len(cal_ran))
)

print("Lower limit : " + str(ci[0]))
print("Higher limit : " + str(ci[1]))

Lower limit : 11.433738235721002
Higher limit : 14.132928430945665

In [49]:
np.mean(a)

np.float64(11.710035)